### PR TITLE
Reduce the file name requirements.

### PR DESCRIPTION
**Pull request by cocomine**
Change file name must start with "input", to the file name must contain "input". Reduce the file name requirements.

### CODE REVIEW

**Comment by cocomine** [comment]
I have been troubled by this condition for a long time, why the "keys" images file cannot be generated, and there is no related error message. Finally, I checked the code and found that the beginning of the file must be "input", otherwise the file cannot be read. In order to reduce the requirements, I changed it to only need to include "input" to read. Because sometimes the file generated by img2img does not meet the condition that the beginning of the file must be "input", so I made these changes.

**Comment by nyukers** [comment]
Prefix "input" must be in filename of frames in /input and /output folders?

**Comment by Lucchirsa** [comment]
I changed the code all of my files are setup the defualt way, Having the input, output, keys and etc. Do I have to change anything else?

**Comment by cocomine** [comment]
> Prefix "input" must be in filename of frames in /input and /output folders?

The input folder is not required, but the output folder must start with "input". That's why I changed the code file name to only include "input".

**Comment by cocomine** [comment]
> I changed the code. I don't understand what else you are saying to change. Do I need to create a new folder, Change a folder or what? I have the Keys, Frames, Results, Output, Input, Folders and all the default ones. What do I need to change besides the code? Now that I changed the code the temporal get won't even show up in A1111

You don't need to change the folder structure if you changed the code. If not you need to change the image file name to start with "input". (No need to change the folder name)

But now the author has merged it. You can try to update the plugin and try again.

**Comment by cocomine** [comment]
@CiaraStrawberry Thanks for accepting the merge.

**Comment by nyukers** [comment]
I took yesterday key frames, thanks. But **ebs-file** did not create. So I don't understand benefit of TemporalKit, in another way I can collect these frames manually.

**Comment by cocomine** [comment]
> I took yesterday key frames, thanks. But **ebs-file** did not create. So I don't understand benefit of using TemporalKit, in another way I can collect these frames manually.

This program does not generate `.ebs` files. You only need to drag the image in the `keys` folder into the **EbSynth** program and the program will automatically fill it in.

For details, please view the teaching document I wrote.
https://github.com/cocomine/TemporalKit#step-7-prepare-ebsynth-data

**Pull request merged**
